addons:
  mysql: "5.6"
branches:
  only:
    - master
language:
  - ruby
notifications:
  email:
    - false
sudo: false
rvm:
  - 2.3.0
  - 2.2.4
  - 2.1.8
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
  - gemfiles/rails50.gemfile
matrix:
  exclude:
    - rvm: 2.1.8
      gemfile: gemfiles/rails50.gemfile
