addons:
  mysql: "5.6"
branches:
  only:
    - master
language:
  - ruby
notifications:
  email:
    - false
sudo: false
rvm:
  - 2.3.0
  - 2.2.4
gemfile:
  - gemfiles/rails40.gemfile
  - gemfiles/rails41.gemfile
  - gemfiles/rails42.gemfile
install: bundle install --deployment
before_script: bundle exec rake dummy:db:create
script: bundle exec rake
